In [1]:
import json
import os
from pathlib import Path
from pprint import pprint
from typing import Optional, Any
from collections import Counter

import torch
import torch.nn as nn
import numpy as np
import wandb
from torch import Tensor
import torch.nn as nn

from datasets import load_from_disk
from transformers import AutoModelForTokenClassification, AutoTokenizer,\
DataCollatorForTokenClassification, TrainingArguments, Trainer, EvalPrediction
import evaluate

from colorama import Fore, Style

In [2]:
from transformers.models.deberta_v2.tokenization_deberta_v2 import DebertaV2Tokenizer
from transformers.models.deberta_v2.modeling_deberta_v2 import DebertaV2ForTokenClassification
from datasets import DatasetDict

In [3]:
model_path = "microsoft/deberta-v3-base"

In [4]:
DATA_DIR = Path(os.getcwd()).parent / "data"
DATA_DIR.mkdir(exist_ok=True)

LABEL_INFO_PATH = DATA_DIR/"label_info.json"
DATASET_PATH = DATA_DIR/"cleaned_ai4privacy_300k_pii"

MODEL_DIR = Path(os.getcwd()).parent / "models"
MODEL_DIR.mkdir(exist_ok=True)

In [5]:
dataset: DatasetDict = load_from_disk(DATASET_PATH) # type:ignore

In [6]:
# label info
with open(LABEL_INFO_PATH) as f:
    label_info: dict = json.load(f)
label2id: dict[str, int] = label_info["label2id"]
id2label = label_info["id2label"]

In [7]:
tokenizer: DebertaV2Tokenizer = AutoTokenizer.from_pretrained(model_path)

model: DebertaV2ForTokenClassification = AutoModelForTokenClassification.from_pretrained(
    model_path, num_labels=len(id2label), id2label=id2label, label2id=label2id)

assert tokenizer.is_fast

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2ForTokenClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
for name, param in model.named_parameters():
    if torch.isnan(param).any():
        print(f"NaN in: {name}")

In [9]:
nn.init.normal_(model.classifier.weight, mean=0.0, std=0.02)
nn.init.zeros_(model.classifier.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], dtype=torch.float16, requires_grad=True)

In [10]:
for name, param in model.named_parameters():
    if torch.isnan(param).any():
        print(f"NaN in: {name}")

In [11]:
for param in model.base_model.parameters():
    param.requires_grad = False
    
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"{name} requires grad")

classifier.weight requires grad
classifier.bias requires grad

In [12]:
Counter([param.dtype for param in model.parameters()])

Counter({torch.float16: 200})

In [13]:
for name, module in model.named_modules():
    module.to(torch.float32) # type:ignore

In [14]:
Counter([param.dtype for param in model.parameters()])

Counter({torch.float32: 200})

In [15]:
example = dataset["train"][0]

In [16]:
text = "Call John Smith at 555-1234"
enc = tokenizer(text, return_offsets_mapping=True)
for tok, off in zip(enc.tokens(), enc["offset_mapping"]):
    print(f"{tok:20s} {off}  →  '{text[off[0]:off[1]]}'")

[CLS]                (0, 0)  →  ''
▁Call                (0, 4)  →  'Call'
▁John                (4, 9)  →  ' John'
▁Smith               (9, 15)  →  ' Smith'
▁at                  (15, 18)  →  ' at'
▁555                 (18, 22)  →  ' 555'
-                    (22, 23)  →  '-'
1234                 (23, 27)  →  '1234'
[SEP]                (0, 0)  →  ''

In [17]:
def tokenize_and_align_labels_single(example):
    """tokenize and align labels for deberta tokenizer.
    since deberta tokenizer will mark space before as part of the next word,
    masks that start the first letter (not white-space) needs this tokenizer.
    it will first get the word_ids that fall in the mask, then label for
    seqeval

    Args:
        example (_type_): _description_

    Returns:
        _type_: _description_
    """
    encoding = tokenizer(
        example["source_text"],
        return_offsets_mapping=True,
        add_special_tokens=True,
        truncation=True,
        max_length=512
    )
    
    word_ids= encoding.word_ids()
    offsets= encoding["offset_mapping"]
    
    # map offsets to their word_id - for sentence-piece tokenization which 
    # tokenizes the space before the word as part of that word
    word_span: dict[int, tuple[int, int]] = {}
    for offset, word_id in zip(offsets, word_ids):
        if word_id is None:
            continue
        if word_id not in word_span:
            word_span[word_id] = offset
        else:
            prev_start, prev_end = word_span[word_id]
            word_span[word_id] = (
                min(prev_start, offset[0]),
                max(prev_end, offset[1])
            )
    
    # map every word_id to its BI tag
    masks = example["privacy_mask"]
    word_to_ent: dict[int, str] = {}
    for mask in masks:
        words_in_mask = sorted(
            word_id
            for word_id, (w_start, w_end) in word_span.items()
            if w_start < mask["end"] and w_end > mask["start"] 
        )

        for word_id in words_in_mask:
            word_to_ent[word_id] = mask["label"]
    
    # add labels and bio tags
    labels: list[int] = []
    bio_tags: list[Optional[str]] = []
    prev_word_id = None
    prev_ent = None
    for word_id in word_ids:
        if word_id is None:
            labels.append(-100)
            bio_tags.append(None)
            
        elif word_id not in word_to_ent:
            labels.append(label2id["O"])
            bio_tags.append("O")
        else: 
            entity = word_to_ent[word_id] 
            
            if word_id != prev_word_id:
                tag = f"I-{entity}" if prev_ent == entity else f"B-{entity}"
                labels.append(label2id[tag])
            else:
                tag = f"I-{entity}"
                labels.append(-100)
                
            bio_tags.append(tag)
            prev_ent = entity
        prev_word_id = word_id
    
    encoding["ner_tags"] = bio_tags
    encoding["labels"] = labels
    return encoding

In [18]:
dataset = dataset.map(tokenize_and_align_labels_single, batched=False)

In [19]:
example = dataset["train"][0]
example_encodings = tokenizer(
    example["source_text"],
    return_offsets_mapping=True,
    add_special_tokens=True,
)
line1 = ""
line2 = ""
line3 = ""
line4 = ""
for word, tag, label, word_id in zip(example_encodings.tokens(), example["ner_tags"], example["labels"], example_encodings.word_ids()):
    tag = str(tag)
    word_id = str(word_id)
    label = str(label)
    max_length = max(len(word), len(tag), len(word_id), len(label))
    line1 += word + " " * (max_length - len(word) + 1)
    line2 += tag + " " * (max_length - len(tag) + 1)
    line3 += label + " " * (max_length - len(label) + 1)
    line4 += word_id + " " * (max_length - len(word_id) + 1)
    
print(line1)
print(line2)
print(line3)
print(line4)

[CLS] ▁Subject : ▁Group ▁Messaging ▁for ▁Admissions ▁Process ▁Good ▁morning , ▁everyone , ▁I ▁hope ▁this ▁message ▁finds ▁you ▁well .  ▁As ▁we ▁continue ▁our ▁admissions ▁processes ,  ▁I ▁would ▁like ▁to ▁update ▁you ▁on ▁the ▁latest ▁developments ▁and ▁key ▁information .  ▁Please ▁find ▁below ▁the ▁timeline ▁for ▁our ▁upcoming ▁meetings :  ▁- ▁          wyn        q          vr         h          053        ▁- ▁Meeting ▁at ▁10    :      20     am     ▁- ▁l         uka        .          burg       ▁- ▁Meeting ▁at ▁21    ▁- ▁qa        hil        .          witt       auer       ▁- ▁Meeting ▁at ▁quarter ▁past  ▁13    ▁- ▁g         hola       m          hos        s          ein        .          ru         schke      ▁- ▁Meeting ▁at ▁9     :      47     ▁PM    ▁- ▁p         d          m          jr         s          y          oz         14         60         [SEP]
None  O        O O      O          O    O           O        O     O        O O         O O  O     O     O        O      O    O     O  O   O   O         O    O           O          O  O  O      O     O   O       O    O   O    O       O             O    O    O            O  O       O     O      O    O         O    O    O         O         O  O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME I-TIME I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME   I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME I-TIME I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME None
-100  0        0 0      0          0    0           0        0     0        0 0         0 0  0     0     0        0      0    0     0  0   0   0         0    0           0          0  0  0      0     0   0       0    0   0    0       0             0    0    0            0  0       0     0      0    0         0    0    0         0         0  0  1          -100       -100       -100       -100       -100       0  0        0   3      -100   -100   -100   0  1          -100       -100       -100       0  0        0   3      0  1          -100       -100       -100       -100       0  0        0   3        4      4      0  1          -100       -100       -100       -100       -100       -100       -100       -100       0  0        0   3      -100   -100   4      0  1          -100       -100       -100       -100       -100       -100       -100       -100       -100
None  0        0 1      2          3    4           5        6     7        7 8         8 9  10    11    12       13     14   15    15 16  17  18        19   20          21         21 22 23     24    25  26      27   28  29   30      31            32   33   34           34 35      36    37     38   39        40   41   42        43        43 44 45         45         45         45         45         45         46 47       48  49     49     49     49     50 51         51         51         51         52 53       54  55     56 57         57         57         57         57         58 59       60  61       62     63     64 65         65         65         65         65         65         65         65         65         66 67       68  69     69     69     70     71 72         72         72         72         72         72         72         72         72         None

In [20]:
# some tokens include whitespace
print(example["source_text"][310:313].replace(" ", "_"))

_10

In [21]:
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

seqeval = evaluate.load("seqeval")

In [22]:
from collections import Counter
def compute_metrics(p: EvalPrediction) -> dict[str, float]:
    predictions, label_ids = p.predictions, p.label_ids
    predictions = np.argmax(predictions, axis=-1)
    
    true_preds = [
        [id2label[str(pred)] for pred, tgt_id in zip(preds_row, labels_row) if tgt_id != -100]
        for preds_row, labels_row in zip(predictions, label_ids)
    ]
    
    true_labels =[
        [id2label[str(tgt_id)] for tgt_id in labels_row if tgt_id != -100]
        for labels_row in label_ids
    ]
    
    # TODO: remove
    all_preds = [label for seq in true_preds for label in seq]
    print("Prediction distribution:", Counter(all_preds))
    
    results = seqeval.compute(predictions=true_preds, references=true_labels)
    
    flat = {}
    if results is not None:
        flat.update({
            "precision": results["overall_precision"],
            "recall": results["overall_recall"],
            "f1": results["overall_f1"],
            "accuracy": results["overall_accuracy"],
        })
        
        for entity, scores in results.items():
            if isinstance(scores, dict): # filter scores for individual labels
                flat[f"{entity}_f1"] = scores["f1"]
                flat[f"{entity}_support"] = scores["number"]
    
    return flat

In [23]:
class WeightedTokenClassificationTrainer(Trainer):
    def __init__(self, *args, class_weights: Optional[torch.Tensor]=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights
        
    def compute_loss(
        self, 
        model: nn.Module, 
        inputs: dict[str, Tensor | Any], 
        return_outputs: bool = False, 
        num_items_in_batch: Tensor | int | None = None
    ) -> Tensor | tuple[Tensor, Any]:
        
        labels = inputs.get("labels")
        outputs = model(**inputs)
        
        if labels is None:
            loss = outputs["loss"] if isinstance(outputs, dict) else outputs.loss
            return (loss, outputs) if return_outputs else loss
        
        logits = outputs["logits"] if isinstance(outputs, dict) else outputs.logits
        weight = None
        if self.class_weights is not None:
            weight = self.class_weights.to(logits.device)
            
        loss_fct = torch.nn.CrossEntropyLoss(weight=weight, ignore_index=-100)
        loss = loss_fct(logits.view(-1, logits.size(-1)), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

In [24]:
wandb.init(project="pii-redaction", name="frozen-backbone-with-tf32")

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/zelluzy/.netrc.
wandb: Currently logged in as: bengid (bengid-) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [25]:
for name, param in model.named_parameters():
    param.requires_grad = False if not name.startswith("classifier") else True
    if param.requires_grad:
        print(f"{name} requires grad")

training_args_phase1 = TrainingArguments(
    output_dir=str(MODEL_DIR),
    report_to="wandb",
    learning_rate=1e-3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    eval_strategy="epoch",
    warmup_ratio=0.1,
    bf16=False,
    tf32=True,
    max_grad_norm=1.0,
)

trainer = WeightedTokenClassificationTrainer(
    model=model,
    args=training_args_phase1,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)
trainer.train()

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

classifier.weight requires grad
classifier.bias requires grad

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 295421, 'B-TIME': 1500, 'B-LASTNAME1': 1499, 'I-STREET': 1384, 'B-EMAIL': 1280, 'B-PASSPORT': 1274, 'B-IDCARD': 1274, 'B-CITY': 948, 'B-SOCIALNUMBER': 935, 'B-IP': 929, 'B-STATE': 920, 'I-BOD': 899, 'B-BUILDING': 886, 'B-STREET': 879, 'B-POSTCODE': 842, 'B-USERNAME': 838, 'I-TEL': 823, 'I-TIME': 787, 'B-DATE': 765, 'B-BOD': 762, 'B-DRIVERLICENSE': 756, 'B-TEL': 734, 'B-PASS': 733, 'B-SEX': 666, 'I-DATE': 611, 'B-TITLE': 540, 'B-COUNTRY': 538, 'I-SOCIALNUMBER': 519, 'I-CITY': 445, 'I-SECADDRESS': 428, 'I-DRIVERLICENSE': 393, 'B-GIVENNAME1': 390, 'B-SECADDRESS': 324, 'I-COUNTRY': 293, 'I-POSTCODE': 247, 'I-SEX': 128, 'B-LASTNAME2': 110, 'I-GEOCOORD': 91, 'B-GIVENNAME2': 74, 'B-GEOCOORD': 64, 'I-LASTNAME1': 41, 'I-USERNAME': 38, 'I-IDCARD': 22, 'I-TITLE': 20, 'B-LASTNAME3': 18, 'I-PASSPORT': 13, 'I-STATE': 8, 'I-GIVENNAME1': 5, 'I-PASS': 4, 'I-EMAIL': 1, 'I-IP': 1})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 294071, 'B-TIME': 1575, 'I-STREET': 1415, 'B-IDCARD': 1299, 'B-PASSPORT': 1235, 'B-EMAIL': 1160, 'B-LASTNAME1': 1134, 'B-USERNAME': 1074, 'B-CITY': 1011, 'B-GIVENNAME1': 960, 'B-IP': 941, 'B-POSTCODE': 927, 'B-STREET': 923, 'B-STATE': 911, 'B-BUILDING': 906, 'B-SOCIALNUMBER': 900, 'B-BOD': 876, 'I-BOD': 855, 'B-TEL': 852, 'B-DRIVERLICENSE': 818, 'B-DATE': 791, 'I-TIME': 780, 'I-TEL': 777, 'B-PASS': 747, 'B-COUNTRY': 674, 'B-SEX': 660, 'I-DATE': 602, 'I-SOCIALNUMBER': 570, 'B-TITLE': 558, 'I-SECADDRESS': 434, 'I-CITY': 418, 'I-DRIVERLICENSE': 410, 'B-SECADDRESS': 366, 'I-COUNTRY': 337, 'I-POSTCODE': 262, 'B-LASTNAME2': 177, 'I-SEX': 155, 'B-GIVENNAME2': 111, 'I-GEOCOORD': 110, 'B-GEOCOORD': 75, 'I-USERNAME': 44, 'I-GIVENNAME1': 39, 'I-PASSPORT': 34, 'I-TITLE': 33, 'I-LASTNAME1': 29, 'I-IDCARD': 19, 'I-PASS': 15, 'I-IP': 13, 'I-STATE': 11, 'B-LASTNAME3': 4, 'I-EMAIL': 2})

TrainOutput(global_step=3740, training_loss=0.24722221292913915, metrics={'train_runtime': 241.1867, 'train_samples_per_second': 248.007, 'train_steps_per_second': 15.507, 'total_flos': 5721316782820488.0, 'train_loss': 0.24722221292913915, 'epoch': 2.0})

In [26]:
for name, param in model.named_parameters():
    if torch.isnan(param).any():
        print(f"NaN in: {name}")

In [27]:
# Unfreeze the backbone
for param in model.base_model.parameters():
    param.requires_grad = True

training_args_phase2 = TrainingArguments(
    output_dir=str(MODEL_DIR),
    learning_rate=2e-5, # low learning_rate
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=5,
    weight_decay=0.01,
    eval_strategy="epoch",
    warmup_ratio=0.1,
    bf16=False,
    tf32=True,
    max_grad_norm=1.0,
)

trainer = WeightedTokenClassificationTrainer(
    model=model,
    args=training_args_phase2,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 290653, 'B-TIME': 1741, 'I-STREET': 1404, 'B-SOCIALNUMBER': 1352, 'B-LASTNAME1': 1284, 'B-EMAIL': 1231, 'B-IDCARD': 1206, 'B-BOD': 1173, 'B-DRIVERLICENSE': 1166, 'B-USERNAME': 1136, 'B-PASSPORT': 1048, 'B-CITY': 1034, 'B-IP': 1019, 'B-STATE': 1003, 'B-BUILDING': 983, 'B-STREET': 969, 'B-SEX': 966, 'B-TEL': 949, 'B-POSTCODE': 948, 'B-TITLE': 918, 'I-TIME': 879, 'I-TEL': 878, 'I-BOD': 876, 'B-DATE': 800, 'B-PASS': 775, 'B-COUNTRY': 759, 'B-GIVENNAME1': 658, 'I-DATE': 567, 'I-SOCIALNUMBER': 546, 'I-DRIVERLICENSE': 505, 'I-CITY': 474, 'I-SECADDRESS': 440, 'B-SECADDRESS': 422, 'B-LASTNAME2': 367, 'I-COUNTRY': 323, 'I-POSTCODE': 249, 'I-SEX': 205, 'B-GIVENNAME2': 188, 'I-LASTNAME1': 152, 'I-USERNAME': 130, 'B-LASTNAME3': 122, 'I-PASSPORT': 110, 'B-GEOCOORD': 100, 'I-GEOCOORD': 98, 'I-IDCARD': 78, 'I-TITLE': 66, 'I-IP': 39, 'I-EMAIL': 32, 'I-GIVENNAME1': 32, 'I-PASS': 29, 'I-STATE': 18})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 290295, 'B-TIME': 1747, 'I-STREET': 1421, 'B-SOCIALNUMBER': 1213, 'B-USERNAME': 1203, 'B-EMAIL': 1182, 'B-IDCARD': 1162, 'B-BOD': 1122, 'B-PASSPORT': 1097, 'B-DRIVERLICENSE': 1073, 'B-LASTNAME1': 1061, 'B-CITY': 1028, 'B-GIVENNAME1': 1017, 'B-STATE': 995, 'B-STREET': 993, 'B-IP': 989, 'B-BUILDING': 973, 'B-POSTCODE': 948, 'I-BOD': 948, 'I-TIME': 942, 'B-SEX': 937, 'B-TEL': 935, 'I-TEL': 904, 'B-TITLE': 860, 'B-DATE': 811, 'B-COUNTRY': 781, 'B-PASS': 765, 'I-SOCIALNUMBER': 626, 'I-DRIVERLICENSE': 591, 'I-DATE': 525, 'I-CITY': 470, 'I-SECADDRESS': 447, 'B-SECADDRESS': 440, 'I-COUNTRY': 326, 'B-GIVENNAME2': 305, 'B-LASTNAME2': 272, 'I-POSTCODE': 252, 'I-SEX': 231, 'I-USERNAME': 163, 'I-LASTNAME1': 148, 'I-PASSPORT': 124, 'B-GEOCOORD': 104, 'I-GEOCOORD': 104, 'I-IDCARD': 104, 'B-LASTNAME3': 95, 'I-EMAIL': 94, 'I-TITLE': 89, 'I-PASS': 68, 'I-IP': 57, 'I-GIVENNAME1': 42, 'I-STATE': 15, 'I-LASTNAME2': 6})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 290430, 'B-TIME': 1723, 'I-STREET': 1426, 'B-IDCARD': 1267, 'B-USERNAME': 1149, 'B-EMAIL': 1146, 'B-SOCIALNUMBER': 1146, 'B-PASSPORT': 1084, 'B-BOD': 1079, 'B-GIVENNAME1': 1030, 'B-CITY': 1010, 'B-STATE': 1001, 'B-LASTNAME1': 1000, 'B-DRIVERLICENSE': 990, 'B-IP': 979, 'B-STREET': 975, 'B-POSTCODE': 964, 'B-BUILDING': 963, 'I-TIME': 937, 'B-SEX': 930, 'B-TEL': 930, 'I-TEL': 891, 'I-BOD': 874, 'B-DATE': 857, 'B-TITLE': 850, 'B-COUNTRY': 800, 'B-PASS': 770, 'I-SOCIALNUMBER': 623, 'I-DRIVERLICENSE': 598, 'I-DATE': 582, 'I-CITY': 465, 'I-SECADDRESS': 444, 'B-SECADDRESS': 440, 'B-GIVENNAME2': 355, 'I-COUNTRY': 344, 'B-LASTNAME2': 272, 'I-POSTCODE': 253, 'I-SEX': 215, 'I-USERNAME': 191, 'I-PASSPORT': 146, 'I-LASTNAME1': 146, 'I-IDCARD': 136, 'I-GEOCOORD': 104, 'B-GEOCOORD': 102, 'I-EMAIL': 100, 'I-PASS': 89, 'I-TITLE': 86, 'I-GIVENNAME1': 62, 'B-LASTNAME3': 60, 'I-IP': 55, 'I-STATE': 23, 'I-LASTNAME2': 4, 'I-BUILDING': 4})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 290710, 'B-TIME': 1710, 'I-STREET': 1418, 'B-IDCARD': 1200, 'B-SOCIALNUMBER': 1168, 'B-EMAIL': 1159, 'B-USERNAME': 1146, 'B-BOD': 1085, 'B-PASSPORT': 1067, 'B-LASTNAME1': 1053, 'B-DRIVERLICENSE': 1039, 'B-CITY': 1011, 'B-STATE': 1003, 'B-IP': 985, 'B-BUILDING': 969, 'B-POSTCODE': 968, 'B-STREET': 962, 'B-TEL': 931, 'B-GIVENNAME1': 929, 'B-SEX': 915, 'I-TIME': 902, 'I-TEL': 884, 'I-BOD': 882, 'B-TITLE': 838, 'B-DATE': 804, 'B-COUNTRY': 774, 'B-PASS': 762, 'I-SOCIALNUMBER': 620, 'I-DRIVERLICENSE': 597, 'I-DATE': 561, 'I-CITY': 469, 'B-SECADDRESS': 442, 'I-SECADDRESS': 441, 'I-COUNTRY': 323, 'B-GIVENNAME2': 303, 'B-LASTNAME2': 289, 'I-POSTCODE': 253, 'I-SEX': 221, 'I-USERNAME': 171, 'I-LASTNAME1': 150, 'I-PASSPORT': 137, 'I-IDCARD': 120, 'I-GEOCOORD': 102, 'B-GEOCOORD': 101, 'I-TITLE': 99, 'I-EMAIL': 99, 'B-LASTNAME3': 92, 'I-GIVENNAME1': 77, 'I-PASS': 67, 'I-IP': 56, 'I-STATE': 25, 'I-LASTNAME2': 6, 'I-BUILDING': 5})

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Prediction distribution: Counter({'O': 290666, 'B-TIME': 1716, 'I-STREET': 1410, 'B-IDCARD': 1224, 'B-SOCIALNUMBER': 1174, 'B-EMAIL': 1153, 'B-USERNAME': 1151, 'B-BOD': 1088, 'B-PASSPORT': 1064, 'B-LASTNAME1': 1060, 'B-DRIVERLICENSE': 1041, 'B-CITY': 1000, 'B-STATE': 1000, 'B-IP': 985, 'B-BUILDING': 962, 'B-STREET': 958, 'B-POSTCODE': 953, 'B-TEL': 935, 'I-TIME': 924, 'B-SEX': 917, 'B-GIVENNAME1': 915, 'I-TEL': 894, 'I-BOD': 873, 'B-TITLE': 849, 'B-DATE': 820, 'B-COUNTRY': 770, 'B-PASS': 766, 'I-SOCIALNUMBER': 621, 'I-DRIVERLICENSE': 588, 'I-DATE': 570, 'I-CITY': 464, 'I-SECADDRESS': 442, 'B-SECADDRESS': 438, 'I-COUNTRY': 323, 'B-GIVENNAME2': 294, 'B-LASTNAME2': 290, 'I-POSTCODE': 250, 'I-SEX': 221, 'I-USERNAME': 174, 'I-LASTNAME1': 166, 'I-PASSPORT': 139, 'I-IDCARD': 120, 'I-TITLE': 102, 'I-EMAIL': 102, 'I-GEOCOORD': 102, 'B-GEOCOORD': 101, 'B-LASTNAME3': 92, 'I-GIVENNAME1': 83, 'I-PASS': 66, 'I-IP': 51, 'I-STATE': 23, 'I-LASTNAME2': 6, 'I-BUILDING': 4})

TrainOutput(global_step=9350, training_loss=0.06486552294562845, metrics={'train_runtime': 1329.5046, 'train_samples_per_second': 112.478, 'train_steps_per_second': 7.033, 'total_flos': 1.3014394085077224e+16, 'train_loss': 0.06486552294562845, 'epoch': 5.0})

In [34]:
for name, param in model.named_parameters():
    if torch.isnan(param).any():
        print(f"NaN in: {name}")

In [29]:
example = dataset["train"][0]
example_encodings = tokenizer(
    example["source_text"],
    return_offsets_mapping=True,
    add_special_tokens=True,
)
line1 = ""
line2 = ""
line3 = ""
line4 = ""
for word, tag, label, word_id in zip(example_encodings.tokens(), example["ner_tags"], example["labels"], example_encodings.word_ids()):
    tag = str(tag)
    word_id = str(word_id)
    label = str(label)
    max_length = max(len(word), len(tag), len(word_id), len(label))
    line1 += word + " " * (max_length - len(word) + 1)
    line2 += tag + " " * (max_length - len(tag) + 1)
    line3 += label + " " * (max_length - len(label) + 1)
    line4 += word_id + " " * (max_length - len(word_id) + 1)
    
print(line1)
print(line2)
print(line3)
print(line4)

[CLS] ▁Subject : ▁Group ▁Messaging ▁for ▁Admissions ▁Process ▁Good ▁morning , ▁everyone , ▁I ▁hope ▁this ▁message ▁finds ▁you ▁well .  ▁As ▁we ▁continue ▁our ▁admissions ▁processes ,  ▁I ▁would ▁like ▁to ▁update ▁you ▁on ▁the ▁latest ▁developments ▁and ▁key ▁information .  ▁Please ▁find ▁below ▁the ▁timeline ▁for ▁our ▁upcoming ▁meetings :  ▁- ▁          wyn        q          vr         h          053        ▁- ▁Meeting ▁at ▁10    :      20     am     ▁- ▁l         uka        .          burg       ▁- ▁Meeting ▁at ▁21    ▁- ▁qa        hil        .          witt       auer       ▁- ▁Meeting ▁at ▁quarter ▁past  ▁13    ▁- ▁g         hola       m          hos        s          ein        .          ru         schke      ▁- ▁Meeting ▁at ▁9     :      47     ▁PM    ▁- ▁p         d          m          jr         s          y          oz         14         60         [SEP]
None  O        O O      O          O    O           O        O     O        O O         O O  O     O     O        O      O    O     O  O   O   O         O    O           O          O  O  O      O     O   O       O    O   O    O       O             O    O    O            O  O       O     O      O    O         O    O    O         O         O  O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME I-TIME I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME   I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME O  O        O   B-TIME I-TIME I-TIME I-TIME O  B-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME I-USERNAME None
-100  0        0 0      0          0    0           0        0     0        0 0         0 0  0     0     0        0      0    0     0  0   0   0         0    0           0          0  0  0      0     0   0       0    0   0    0       0             0    0    0            0  0       0     0      0    0         0    0    0         0         0  0  1          -100       -100       -100       -100       -100       0  0        0   3      -100   -100   -100   0  1          -100       -100       -100       0  0        0   3      0  1          -100       -100       -100       -100       0  0        0   3        4      4      0  1          -100       -100       -100       -100       -100       -100       -100       -100       0  0        0   3      -100   -100   4      0  1          -100       -100       -100       -100       -100       -100       -100       -100       -100
None  0        0 1      2          3    4           5        6     7        7 8         8 9  10    11    12       13     14   15    15 16  17  18        19   20          21         21 22 23     24    25  26      27   28  29   30      31            32   33   34           34 35      36    37     38   39        40   41   42        43        43 44 45         45         45         45         45         45         46 47       48  49     49     49     49     50 51         51         51         51         52 53       54  55     56 57         57         57         57         57         58 59       60  61       62     63     64 65         65         65         65         65         65         65         65         65         66 67       68  69     69     69     70     71 72         72         72         72         72         72         72         72         72         None

In [30]:
Counter([param.dtype for param in model.parameters()])

Counter({torch.float32: 200})

In [31]:
import html as html_lib

def log_pii_test_results(
    trainer,
    test_dataset,
    tokenizer,
    table_name: str = "pii_test_results",
    run: Optional[wandb.sdk.wandb_run.Run] = None,
) -> wandb.Table:
    id2label = trainer.model.config.id2label
    pred_output = trainer.predict(test_dataset)
    pred_ids = np.argmax(pred_output.predictions, axis=-1)
    true_ids = pred_output.label_ids

    table = wandb.Table(columns=["id", "annotated_sequence", "f1", "precision", "recall", "tp", "fp", "fn"])

    for i in range(len(test_dataset)):
        tokens, true_labels, pred_labels = [], [], []
        for token_id, true_id, pred_id in zip(test_dataset[i]["input_ids"], true_ids[i], pred_ids[i]):
            if true_id == -100:
                continue
            tokens.append(tokenizer.convert_ids_to_tokens(token_id))
            true_labels.append(id2label[str(true_id)])
            pred_labels.append(id2label[str(pred_id)])

        tp = fp = fn = 0
        for true, pred in zip(true_labels, pred_labels):
            if true != "O" and pred == true:  tp += 1
            elif true != "O" and pred != true: fn += 1
            elif true == "O" and pred != "O":  fp += 1

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

        parts = []
        for token, true, pred in zip(tokens, true_labels, pred_labels):
            t = html_lib.escape(token)
            if true != "O" and pred == true:
                badge = f'<sup style="font-size:9px;padding:1px 4px;border-radius:3px;background:#C0DD97;color:#27500A">{html_lib.escape(true)}</sup>'
                parts.append(f'<span style="background:#C0DD97;color:#27500A;font-weight:500;padding:2px 4px;border-radius:3px;margin:1px 2px;display:inline-block">{t}{badge}</span>')
            elif true != "O" and pred != true:
                label = html_lib.escape(f"{true}→{pred}")
                badge = f'<sup style="font-size:9px;padding:1px 4px;border-radius:3px;background:#F7C1C1;color:#791F1F">{label}</sup>'
                parts.append(f'<span style="background:#F7C1C1;color:#791F1F;font-weight:500;padding:2px 4px;border-radius:3px;margin:1px 2px;display:inline-block">{t}{badge}</span>')
            elif true == "O" and pred != "O":
                badge = f'<sup style="font-size:9px;padding:1px 4px;border-radius:3px;background:#FAC775;color:#633806">{html_lib.escape(pred)}</sup>'
                parts.append(f'<span style="background:#FAC775;color:#633806;font-weight:500;padding:2px 4px;border-radius:3px;margin:1px 2px;display:inline-block">{t}{badge}</span>')
            else:
                parts.append(f'<span style="margin:1px 2px;display:inline-block">{t}</span>')

        seq_html = '<div style="font-family:monospace;font-size:12px;line-height:2">' + "".join(parts) + "</div>"
        table.add_data(i, wandb.Html(seq_html), round(f1, 4), round(precision, 4), round(recall, 4), tp, fp, fn)

    (run or wandb).log({table_name: table})
    return table

In [32]:
log_pii_test_results(trainer, dataset["test"], tokenizer)

Prediction distribution: Counter({'O': 287761, 'B-TIME': 1754, 'I-STREET': 1303, 'B-USERNAME': 1220, 'B-EMAIL': 1174, 'B-IDCARD': 1170, 'B-PASSPORT': 1123, 'B-LASTNAME1': 1108, 'B-SOCIALNUMBER': 1108, 'B-BOD': 1100, 'B-DRIVERLICENSE': 1071, 'B-IP': 1050, 'B-CITY': 997, 'B-STATE': 980, 'B-GIVENNAME1': 971, 'B-SEX': 962, 'B-STREET': 944, 'I-TIME': 936, 'B-POSTCODE': 933, 'B-BUILDING': 931, 'B-TEL': 900, 'B-TITLE': 876, 'B-DATE': 856, 'I-TEL': 833, 'I-BOD': 798, 'B-COUNTRY': 788, 'B-PASS': 779, 'I-DATE': 625, 'I-SOCIALNUMBER': 565, 'I-DRIVERLICENSE': 527, 'I-CITY': 471, 'B-SECADDRESS': 420, 'I-SECADDRESS': 417, 'I-POSTCODE': 384, 'I-COUNTRY': 334, 'B-LASTNAME2': 288, 'B-GIVENNAME2': 252, 'I-USERNAME': 221, 'I-SEX': 207, 'I-LASTNAME1': 172, 'I-IDCARD': 138, 'I-EMAIL': 134, 'I-GIVENNAME1': 126, 'I-TITLE': 124, 'B-GEOCOORD': 111, 'I-GEOCOORD': 111, 'I-PASSPORT': 104, 'B-LASTNAME3': 93, 'I-PASS': 93, 'I-IP': 58, 'I-STATE': 14, 'I-LASTNAME2': 6, 'I-BUILDING': 1})

In [33]:
wandb.finish()